[pytest]
python_files = tests/test_*.py
python_classes = Test*
python_functions = test_*
addopts = -q
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning
    ignore:Using `httpx` with `starlette.testclient` is deprecated:DeprecationWarning
