[tox]
envlist = py,typecheck
skipsdist = true

[testenv]
deps =
    -r requirements.txt
    pytest>=8.0.0
commands =
    python -m pytest
setenv =
    PYTHONPATH = {toxinidir}

[testenv:typecheck]
deps =
    -r requirements.txt
commands =
    python -m pyright
