from app.core.config import settings


class UsageLimits:
    MAX_INPUT_CHARACTERS = settings.MAX_INPUT_CHARACTERS
    MAX_OUTPUT_TOKENS = settings.MAX_OUTPUT_TOKENS
    MAX_RECENT_MESSAGES = settings.MAX_RECENT_MESSAGES
    MAX_DAILY_PLAYER_REQUESTS = settings.MAX_DAILY_PLAYER_REQUESTS
    MAX_DAILY_PLAYER_INPUT_TOKENS = settings.MAX_DAILY_PLAYER_TOKENS
    MAX_CAMPAIGNS_PER_PLAYER = settings.MAX_CAMPAIGNS_PER_PLAYER
    MAX_CAMPAIGN_TURNS = settings.MAX_TURNS_PER_CAMPAIGN
    MAX_DAILY_PROJECT_REQUESTS = settings.MAX_DAILY_PROJECT_REQUESTS
    MAX_DAILY_PROJECT_TOKENS = settings.MAX_DAILY_PROJECT_TOKENS
